@startuml
skinparam shadowing false
skinparam sequence {
  Shadowing false
  ActorBorderColor Black
  ActorBackgroundColor DarkGray

  ParticipantBackgroundColor #e6e6e6
  ParticipantBorderColor DarkGray

  BackgroundColor Red
  FontColor Black
  ArrowColor Black
  LifeLineBorderColor Gray
  LifeLineBackgroundColor LightGray
}

actor "Utente" as U
participant "<<boundary>>\n EnglishAuctionPage" as PA
participant "<<control>>\n AuctionController" as CA
participant "<<entity>>\n EnglishAuction" as A
participant "<<boundary>>\n CreateEnglishAuctionForm" as F
participant "<<boundary>>\n Feedback" as N

activate U
U -> PA : 1. "create English Auction"
activate PA
PA -> CA : 2. createEnglishAuction()
activate CA
CA -> F : 3. showForm()
activate F
deactivate F
U -> F : 4. "fill the form"
activate F
CA -> F : 5. getFormData()
F --> CA : return form data
deactivate F
||20||

CA -> CA : 6. processFormData() 
alt input correct
    CA -> A : 7. <<create>>
    activate A
    A --> CA : return auction
    deactivate A
    ||20||

    CA -> N : 8. showSuccessNotification()
    activate N
    N --> PA : return successMessage
    deactivate N
    ||20||
else input not correct
    CA -> N : 9. showErrorNotification()
    activate N
    N --> PA : return errorMessage
    deactivate N
    ||20||
end
||20||

deactivate CA
deactivate PA
deactivate U
@enduml